
export enum Curriculum {
  IGCSE = 'IGCSE',
  MYP = 'MYP'
}

export interface Assessment {
  id: string;
  title: string;
  date: string;
  score: number;
  maxScore: number;
  percentage: number;
  whatWentWell: string;
  whatToImprove: string;
  type: 'Formative' | 'Summative';
}

export const DEFAULT_TERM_EXAMS = [
  'First Midterm Examination', 
  'Term End Examination', 
  'Second Midterm Examination', 
  'Year End Examination'
];

export interface TermAssessment {
  id: string;
  examType: string;
  date: string;
  score: number;
  maxScore: number;
  percentage: number;
  whatWentWell: string;
  actionPlan: string;
}

export interface Resource {
  id: string;
  name: string;
  type: 'pdf' | 'link' | 'image' | 'other';
  url: string; 
  category?: 'material' | 'study_resource' | 'term_syllabus' | 'assessment' | 'marking_scheme' | 'answer_script' | 'diff_support' | 'diff_core' | 'diff_extension';
  assessmentType?: 'Formative' | 'Summative';
  termExamName?: string;
}

export interface BatchResource extends Resource {
    batchId: string;
    topicId: string;
    uploadedBy: 'ADMIN';
    dateAdded: number;
}

export interface Topic {
  id: string;
  title: string;
  description: string;
  resources: Resource[];
  completed: boolean;
}

export interface AttendanceRecord {
  date: string;
  status: 'present' | 'absent' | 'late';
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: number;
}

export interface TuitionTask {
  id: string;
  title: string;
  description: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  completed: boolean;
  aiContextPrompt?: string; 
  chatHistory?: ChatMessage[];
}

export interface TuitionReflection {
  id: string;
  date: string;
  topicDiscussed: string;
  understood: string;
  questions: string;
}

export interface StudentWork {
  id: string;
  name: string;
  url: string;
  date: string;
}

export interface BehaviorRecord {
  id: string;
  date: string;
  type: 'Merit' | 'Demerit';
  category: string;
  description: string;
  points: number;
}

export interface PredictedGradeLog {
  id: string;
  date: string;
  subject: string;
  grade: string;
  comment: string;
}

export interface SchoolAttendanceRecord {
  date: string;
  status: 'Present' | 'Absent' | 'Late' | 'Excused';
  reason?: string;
}

export interface SchoolReport {
  id: string;
  title: string;
  url: string;
  date: string;
}

export interface ATLSkill {
    id: string;
    category: 'Communication' | 'Social' | 'Self-Management' | 'Research' | 'Thinking';
    skill: string;
    selfRating: number; // 1-5
    evidence: string;
    aiAdvice?: string;
    taskContext?: string;
}

export interface IBAttribute {
    id: string;
    attribute: string; 
    reflection: string;
    aiFeedback?: string;
    taskContext?: string;
}

export interface TypingStats {
    wpm: number;
    accuracy: number;
    lessonsCompleted: number;
}

export interface VocabWord {
    id: string;
    word: string;
    definition: string;
    origin?: string; // Auto-generated by AI
    example: string;
    mastered: boolean;
}

export interface ChallengeImage {
    id: string;
    name: string;
    base64: string; 
    dateAdded: number;
}

export interface AssessmentTask {
  id: string;
  batchId: string;
  curriculum: Curriculum;
  category: 'AO1' | 'AO2' | 'AO3' | 'CritA' | 'CritB' | 'CritC' | 'CritD';
  title: string;
  questionPaperUrl: string; 
  markingSchemeBase64: string; 
  markingSchemeMimeType: string;
  dateCreated: number;
}

export interface SyllabusPortion {
  id: string;
  batchId: string;
  examName: string; 
  syllabusText: string; 
  lastUpdated: number;
}

// Added PeerMarkingTask interface for collaborative student interactions
export interface PeerMarkingTask {
  id: string;
  title: string;
  batchId: string;
  studentId: string;
  studentName: string;
  assignedMarkerId: string;
  assignedMarkerName: string;
  scriptUrl: string;
  schemeUrl: string;
  status: 'Pending' | 'Marking' | 'Completed';
  dateSubmitted: number;
}

export interface Student {
  id: string;
  username?: string; 
  password?: string; 
  name: string;
  curriculum: Curriculum;
  batch: string;
  assessments: Assessment[];
  termAssessments: TermAssessment[];
  topics: Topic[];
  attendance: AttendanceRecord[]; 
  tuitionTasks: TuitionTask[];
  tuitionReflections: TuitionReflection[];
  tuitionWork?: StudentWork[];
  differentiationResources: Resource[];
  targetGrade?: string; 
  chatHistory?: ChatMessage[]; 
  aiUsage?: { date: string; count: number }; 
  
  atlSkills?: ATLSkill[];
  ibAttributes?: IBAttribute[];
  typingStats?: TypingStats;
  vocabList?: VocabWord[];
  empowermentUsage?: { date: string; count: number };

  behaviorRecords?: BehaviorRecord[];
  predictedGradeLogs?: PredictedGradeLog[];
  schoolAttendance?: SchoolAttendanceRecord[];
  schoolReports?: SchoolReport[];
  
  challengePoints?: number;
  challengeHistory?: string[]; 
}